# Generated by Django 5.2.7 on 2025-11-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="stock",
            field=models.ManyToManyField(
                blank=True, related_name="stock", to="stock.stock"
            ),
        ),
    ]
